### ISSUE TITLE
Parameter prefixes

### ISSUE THREAD

**Issue by billxinli** [goodybag/mongo-sql#119]
Is there any way to override the parameter prefixes for values from `$1`, `$2`, etc to `?` Or have toString() return the actual pg statement?

**Comment by jrf0110** [comment]
Unfortunately, the PG-specific values stuff is pretty entrenched in the codebase. I really wish I had abstracted that portion away so it would be easier to change. However, as a temporary fix, you could do something like this:

```javascript
var mosql = require('mongo-sql');

mosql.old = mosql.sql;

mosql.sql = function( query ){
  var result = mosql.old( query );

  return {
    values: result.values

  , toString: function(){
      // Replace all with `?`
      return result.toString().replace( /\$\d+/g, '?' )
      // OR:
      // Replace all with actual values
      return result.toString().replace( /\$\d+/g, function( str ){
        var i = +str.substring(1) - 1;
        var val = result.values[ i ];
        return typeof val === 'string' ? "'" + val + "'" : val;
      });
    }
  }
};
```

Hope this helps

**Comment by billxinli** [comment]
Thank @jrf0110! This helps!
