### ISSUE TITLE
Support distinct on( expression )

### ISSUE THREAD

**Issue by jrf0110** [goodybag/mongo-sql#123]
http://www.postgresql.org/docs/current/static/sql-select.html#SQL-DISTINCT

**Comment by albinekb** [comment]
@jrf0110 I would like to help implementing this. How should it be configured?

Maybe a new `distinct` key with `{ on: "column_name }`?

**Comment by albinekb** [comment]
Looks like it's already implemented? 😍  https://github.com/goodybag/mongo-sql/blob/master/docs/query-helpers.md#helper-distinct

**Comment by jrf0110** [comment]
Well look at that :D
