### ISSUE TITLE
Conflict not working on mosql.j0.hn

### ISSUE THREAD

**Issue by LinusU** [goodybag/mongo-sql#134]
The following example currently doesn't provide the correct output for queries using `conflict`

```js
{
  type: 'insert'
, table: 'users'
, values: {
    name: 'Bob'
  , email: 'bob@bob.com'
  }
, conflict: {
    target: {
      // When the email column raises a unique exception
      column: 'email'
    }
  , action: {
      // Go ahead and update the name to the name we tried to use
      update: { name: '$excluded.name$' }
      // Optionally, supply a condition for which resolve the conflict in this way
    , where: { id: { $lt: 100 } }
    }
  }
}
```

Also, no error is provided when unknown fields are added to objects, I think it would be very nice if instead of just dropping the conflict part (I'm assuming an old version is deployed) it would say `Error: Unknown attribute "conflict"`.

**Comment by jrf0110** [comment]
At some point, we removed all of the UMD boilerplate from the codebase and I never fixed the mosql site. Lemme see if I can just fix that real fast

**Comment by jrf0110** [comment]
Moved here https://github.com/jrf0110/mongo-sql-tool/pull/10
