### ISSUE TITLE
Please follow proper semver versioning

### ISSUE THREAD

**Issue by Meaglin** [goodybag/mongo-sql#138]
The following commit changed output of existing functions:
https://github.com/goodybag/mongo-sql/commit/704adff956e75b7732f419359cf88a96c2c83540

According to semver this requires a major version, please follow this.
We had several failing test in our system due to 'just' a patch version.

**Comment by LinusU** [comment]
As I understood that commit, it was rather a bugfix, the only thing that was changed was the faulty behaviour of an edge case. It was never documented to work in the old way, and thus one shouldn't rely on it.

I understand that these situations is very hard though, maybe it would have been better with a major bump, but I think it's too late for that now. Changing back would break it for people that are relying on the new behaviour...

**Comment by jrf0110** [comment]
@Meaglin sorry for the late reply. @LinusU's comment just notified me about it. I definitely saw it as a simple bugfix originally, but I can understand where you're coming from. We'll try to keep this in mind moving forward and probably be more aggressive to bump minor and major versions.
