### ISSUE TITLE
Passing undefined as returning throws error

### ISSUE THREAD

**Issue by LinusU** [goodybag/mongo-sql#139]
Similar to my other opened issues, I have found another case of passing undefined :)

```js
{
  type: 'insert',
  table: 'user',
  values: { name: 'Linus' },
  returning: undefined
}
```

I'm simply forwarding the `returning` value that is getting passed to my function, so having this be a noop instead of throwing would be nice.

**Comment by jrf0110** [comment]
Hrmm I'm actually not having any issues with that http://mosql.j0.hn/#/snippets/9s

**Comment by LinusU** [comment]
Hmm, yeah you are correct 🤔 

I thought I just tested it on that very site... Hmm, I don't know what the issue actually is here, I'll dig and report back :)

**Comment by LinusU** [comment]
I'm an idiot 😆 

I sent in the object `{ returning: undefined }` _as the value of returning_

**Comment by jrf0110** [comment]
Ahhh gotcha. Glad you got it figured out :)

**Comment by LinusU** [comment]
An intersting thing though, `returning: false` gives no error, `returning: true` does... Maybe that isn't so weird though...
