### ISSUE TITLE
Playgroud social login should not ask for write access for user profile.

### ISSUE THREAD

**Issue by ravshansbox** [goodybag/mongo-sql#145]
<img width="455" alt="screen shot 2017-03-17 at 6 01 21 am" src="https://cloud.githubusercontent.com/assets/1499188/24024725/6c53bae2-0ad7-11e7-87e5-41f49da5d121.png">

**Comment by jrf0110** [comment]
Totally right. That seems odd that I did that. Will get on that, thanks!

**Comment by jrf0110** [comment]
Will be taken care of in https://github.com/jrf0110/mongo-sql-tool/issues/11
