### ISSUE TITLE
writing case expression

### ISSUE THREAD

**Issue by bakhodir10** [goodybag/mongo-sql#149]
I was using knex and wrote that query.

knex()
  .columns(
      'id',
       this.knex.raw('case when u.password is null then true else false end as condition'))
       .select()
        .from(`users as u`);

Now, I am using mongo-sql.
How can I write the code in mongo-sql ?
I want to get user's password property as condition whether it is true or not.
Any ideas ?

**Comment by jrf0110** [comment]
@bakhodirsbox something like this work? http://mosql.j0.hn/#/snippets/av

**Comment by bakhodirsbox** [comment]
@jrf0110 yes, it is working. Thanks
