### ISSUE TITLE
Alias in sub query bug

### ISSUE THREAD

**Issue by PaulGrimshaw** [goodybag/mongo-sql#150]
There appears to be a problem with alias in a sub query:

Example below:

```
let moQuery = {
    type:  "select",
    table: {
        type: "select",
        table: "myTable",
        alias: "mt"
    },
    alias: "mt2"
}
console.log(builder.sql(moQuery).toString())
```

Result is:

`select "mt2".* from (select "myTable".* from "myTable") "mt" "mt2"`

But should be:

`select "mt2".* from (select "mt".* from "myTable"  "mt") "mt2"`

**Comment by PaulGrimshaw** [comment]
If someone could point me to the relevant part of the source that would be very helpful.

**Comment by jrf0110** [comment]
@PaulGrimshaw Whenever I implemented this way back when, I had a very specific use-case. I had never covered the case of needing to also alias the inner-most query. So table aliases refer to the context in which they are embedded, which I realize is counter-intuitive:

See http://mosql.j0.hn/#/snippets/1d

I'd be happy to accept a PR that makes this behave like you posted (and we minor or major bump accordingly).

I'd start looking here:

* https://github.com/goodybag/mongo-sql/blob/master/test/select.js#L587-L630
* https://github.com/goodybag/mongo-sql/blob/master/helpers/query/table.js

I apologize in advance for the messy code :)

**Comment by PaulGrimshaw** [comment]
Great, I'll have a go :-)
