### ISSUE TITLE
Why are column and table names etc quoted with double-quotation marks not backticks? 

### ISSUE THREAD

**Issue by Sijan117** [goodybag/mongo-sql#152]
When using this with something like mysqljs, if i simply feed the resulting query generated using this package it throws an error in my SQL syntax. I can easily go around this with something like, 

````js 
const sql = mosql.sql(query);
let sqlString = sql.toString().replace(/"/g, '`');
````

I was just wondering what the reason is for using double quotes in the first place, I thought the standard for these reserved words in mySQL is using backticks. 

Is there perhaps some config setting to change this, or am I missing something trivial here?

**Comment by jrf0110** [comment]
You're not missing something trivial. This library was somewhat naively written years ago just to support Postgres. I sorely regret not having a concept of dialect.

That being said, I do believe it's in the SQL spec to use double quotes for database object names like columns and aliases.

There is an issue somewhere to track dialect support, but I'm on my phone right now and it's kind of hard to find

**Comment by jinger89** [comment]
I am running into the same problem, it is frustrating.

This library is essentially a clone that supports dialects: https://github.com/2do2go/json-sql
