### ISSUE TITLE
Missing parentheses when using null in $in or $nin statement

### ISSUE THREAD

**Issue by james-siteclick** [goodybag/mongo-sql#174]
Using the MoSQL generator, and entering the following query:

```
{
  "type": "select",
  "table": "users",
  "where" : {
    "field_a" : 1,
    "field_b" : {"$in" : [null, 2]}
  }
}
```
Generates:
```
select "users".* from "users" where "users"."field_a" = $1 and "users"."field_b" in ($2) or "users"."field_b" is null
```

However I would expect it to generate:
```
select "users".* from "users" where "users"."field_a" = $1 and ("users"."field_b" in ($2) or "users"."field_b" is null)
```

Otherwise the logic is a & b | c rather than a & (b | c)

The same happens when using $nin.

Version is 5.0.4

**Comment by jrf0110** [comment]
@sedrik would you be up for handling this? Should just be a matter of a adding parenthesis in the `null` cases

**Comment by sedrik** [comment]
Sure, should be easy to fix
