### ISSUE TITLE
$in query should be dropped if array is empty

### ISSUE THREAD

**Issue by ravshansbox** [goodybag/mongo-sql#184]

**Comment by CvBlixen** [comment]
This is very similar to #124 and I have also had problems with that.

I will submit a PR shortly. 🙂

**Comment by ravshansbox** [comment]
I've tested with v6.1.0, it is still generating incorrect output.
For query object `{type: 'select',table: 'table1',where: { a: { $in: [] } }}`, it is generating `select "table1".* from "table1" where false`, but expected `select "table1".* from "table1"`

**Comment by CvBlixen** [comment]
Oh! But I thought that was how it was supposed to be. 🤔 

There's even a test that verifies that this is the case:

https://github.com/goodybag/mongo-sql/blob/master/test/conditions.js#L392

I think the rationale behind this is that false is safer than (implied) true in for instance the case of an update query.

I propose the following addition to the docs:

https://github.com/goodybag/mongo-sql/pull/185

**Comment by jrf0110** [comment]
Looks like this was changed in https://github.com/goodybag/mongo-sql/pull/180

After reading @johansteffner's rationale, I tend to agree with him. If you set the `$in` operator and supply an empty list, then

**Comment by ravshansbox** [comment]
I think better option is to drop/ignore, because if we `and` the output with another predicate result will be `false`, where as we are expecting it to be `true`.

**Comment by ravshansbox** [comment]
We do the same with `undefined` values, we just drop them.

**Comment by ravshansbox** [comment]
After thinking a while, I got the idea behind it. I agree with @CvBlixen, it's working the way it was supposed, thanks.
